apiVersion: "v1"
kind: "Service"
metadata:
  name: "k8s-resource-watcher-service"
  labels:
    app: "k8s-resource-watcher"
spec:
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  selector:
    app: "k8s-resource-watcher"
  type: "ClusterIP"
